### ISSUE TITLE
Your math is wrong

### ISSUE THREAD

**Issue by BlueRaja** [nolanlawson/optimize-js#13]
You list 9.42ms --> 5.27ms as a 128.73% improvement, but list 12.76ms --> 1.75ms as an 86.29% improvement!?

The actual correct percentages are _"78.75% and 629.14% increases in speed (respectively)"_, or equivalently, _"44.06% and 86.29% decrease in runtime"_.

The formulas are:
Increase in speed: `old/new - 1`
Decrease in runtime: `1 - new/old`

**Comment by nolanlawson** [comment]
Fixed in https://github.com/nolanlawson/optimize-js/pull/14 ; the improvement numbers were indeed miscalculated by a bit. Thanks for reporting!
