### ISSUE TITLE
Comparison with Google's Closure Compiler?

### ISSUE THREAD

**Issue by prashnts** [nolanlawson/optimize-js#15]
Great project! I was wondering if there could be a comparison with [Closure Compiler](https://github.com/google/closure-compiler/)? Willing to do it if you think it'd be worth.

**Comment by NeXTs** [comment]
Couldn't they be used together? Complementing each other

**Comment by nolanlawson** [comment]
Sure, I'd be interested in seeing a comparison. Please feel free to compare the two and then write a blog post about it, and I'll be glad to link to it from the README. :)
