### ISSUE TITLE
similar repositories  using js engine tricks ?

### ISSUE THREAD

**Issue by p2227** [nolanlawson/optimize-js#17]
some repositories  like this and this:
https://github.com/sindresorhus/to-fast-properties

optimize js by using some js engine tricks 
i want to collect them
do anyone know other similar repositories  ?

**Comment by nolanlawson** [comment]
Sure, there's a "see also" section. I'll add this and another one I'm aware of: https://github.com/TheLarkInn/V8LazyParseWebpackPlugin
