### ISSUE TITLE
Option to set input source map

### ISSUE THREAD

**Issue by sanex3339** [nolanlawson/optimize-js#18]
I will be happy if you create ability to set input source map (after obfuscation or minification) for correct generation of output source map.

I want to use it here 
https://github.com/sanex3339/javascript-obfuscator/blob/dev/src/JavaScriptObfuscatorInternal.ts#L74-L80

with combination of 
https://github.com/nolanlawson/optimize-js/issues/5

**Comment by nolanlawson** [comment]
closing as a dup of #5, seems to be the same feature
