### ISSUE TITLE
Benchmark script's improvement calculation is off a bit

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/optimize-js#19]
See https://github.com/nolanlawson/optimize-js/pull/14#issuecomment-249357864, need to re-run the benchmark and double-check the math to make sure everything is correct down to two decimal places.

**Comment by robpalme** [comment]
It's definitely off.  The results for Chrome & Lodash show a positive improvement, when actually it's a performance regression.

Minified: 20.70ms
Minified+Opt: 24.45ms
Stated Improvement:  3.78%  <-- wrong

**Comment by jdalton** [comment]
Just a heads up after`optimize-js`  was release I [updated](https://github.com/lodash/lodash/wiki/Changelog#sept-20-2016--diff--docs) Lodash to [use this technique](https://github.com/lodash/lodash/commit/5c912bcc62d385084cf7f9a13b5ac850a7e72be0).

**Comment by nolanlawson** [comment]
@robpalme Yeah thanks, something got messed up. I'll just re-do the calculations in Excel and fix the README for now.

@jdalton Cool, okay, now I understand #20. :) Will need to update Lodash when I re-run the benchmarks; most likely optimize-js will have zero impact.

Note though that your fix will cause Uglify to remove the parentheses, and then optimize-js will not add them back because it currently doesn't detect named functions that are immediately-invoked.

**Comment by nolanlawson** [comment]
OK, it turned out that #14 actually introduced some errors in the calculation (while fixing other errors). That should teach me to triple-check PRs before merging... >_<

In any case I've re-run all the calculations in Excel and quadruple-checked that everything looks right. See a1c41a07dc6ba6815255ba78c32d016370495316 for the fix.
