### ISSUE TITLE
Bad Readme example?

### ISSUE THREAD

**Issue by tomByrer** [nolanlawson/optimize-js#38]
Seems the before & after are the same?  Or should I not report bugs at 1am? ;)

Readme
----

Example input:

```js
!function (){}()
function runIt(fun){ fun() }
runIt(function (){})
```

Example output:

```js
!(function (){})()
function runIt(fun){ fun() }
runIt((function (){}))
```

**Comment by vigneshshanmugam** [comment]
Check the parenthesis being added in the output.

**Comment by nolanlawson** [comment]
Yes, please note parens.
