### ISSUE TITLE
Is there a browser side version?

### ISSUE THREAD

**Issue by Josema** [nolanlawson/optimize-js#42]
I would like to use optimize-js on the browser. Is that possible?

**Comment by nolanlawson** [comment]
Sure, you can try browserifying it, but note that it will probably be quite heavy and therefore remove any benefit of the optimized code.

**Comment by Josema** [comment]
I tried browserifying and just added a `window.optimizeJs = optimizeJs;` to export the function. But the ouput is always the same as the input.
https://plnkr.co/edit/bQH6WME3nSV8DjDiEynr?p=preview
