### ISSUE TITLE
Not as optimized for Webpack as it could be

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/optimize-js#7]
Looking at the Webpack output, it appears to me that those modules that are passed in as an _array_ to another function (and are therefore not wrapped) should probably be wrapped. As with Browserify, I'd wager it's rare for a module not to be immediately `require()`d, meaning that wrapping all of them would provide a perf boost.

Need a reasonably-sized Webpack bundle in order to test this and confirm, though. **TODO:** find some large-ish library that is built with Webpack.

**Comment by nolanlawson** [comment]
Example input and output: https://gist.github.com/vigneshshanmugam/89867ac713d1160c865c53c93e47470a

**Comment by ggoodman** [comment]
For science: https://gist.github.com/ggoodman/72c4366ebe9bee47ad158527ee4c5e93

**Comment by TheLarkInn** [comment]
Did we test these w/ the [V8LazyParseWebpackPlugin](https://github.com/thelarkinn/v8lazyparsewebpackplugin)?

**Comment by ggoodman** [comment]
@TheLarkInn if I had some guidance on moving to Webpack 2, I would try it out.

**Comment by TheLarkInn** [comment]
That plugin _may_ work with webpack 1 also, but what specifically do you need help with for webpack 2.

**Comment by nolanlawson** [comment]
This may be a good first patch, given that you basically just need to add a new test case (`input.js` and `output.js`) and then add a new condition to check if the function is inside an array inside of a call expression. [ASTExplorer](https://astexplorer.net/) is very helpful here.

**Comment by vigneshshanmugam** [comment]
@TheLarkInn Does lazyparseplugin adds the parans for the modules in array?

**Comment by TheLarkInn** [comment]
It sure does!! If you have a large app feel free to try it. Only catch is that I believe you have to tell UglifyJsPlugin compress option to set `negate_iife: false`.

**Comment by TheLarkInn** [comment]
@vigneshshanmugam if you have an app that we can test with I'd be interested to see the statistics.

**Comment by vigneshshanmugam** [comment]
@TheLarkInn I tried it and updated the gist. It fails to wrap the inner functions as well.

**Comment by TheLarkInn** [comment]
Awesome!!! I intentionally didn't wrap the inner functions inside modules because I wasn't sure the benefit, but it's definitely possible to use a webpack parser plugin to do this.

**Comment by vigneshshanmugam** [comment]
Ahh got it.. But i believe the benchmarks in the README includes the wrapping  for inner functions as well.. Anyways as you said, its possible to do this :)

**Comment by nolanlawson** [comment]
Fixed in https://github.com/nolanlawson/optimize-js/pull/33
